# Generated by Django 5.1.6 on 2025-03-05 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "état de jeu",
                "verbose_name_plural": "états de jeu",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="corps")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                ("rating", models.FloatField(default=0, verbose_name="note")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "commentaire",
                "verbose_name_plural": "commentaires",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GamePlayed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                ("game_level", models.CharField(max_length=100, verbose_name="niveau")),
                ("game_duration", models.FloatField(verbose_name="durée")),
                ("game_tries", models.IntegerField(verbose_name="essais")),
                ("game_score", models.FloatField(verbose_name="score")),
                (
                    "game_finished",
                    models.BooleanField(default=False, verbose_name="terminé"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
                (
                    "game_state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_app.gamestate",
                        verbose_name="état de jeu",
                    ),
                ),
            ],
            options={
                "verbose_name": "partie",
                "verbose_name_plural": "parties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GameStateCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji", models.CharField(max_length=100, verbose_name="emoji")),
                ("matched", models.BooleanField(default=False, verbose_name="associé")),
                (
                    "game_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="api_app.gamestate",
                        verbose_name="état de jeu",
                    ),
                ),
            ],
            options={
                "verbose_name": "carte",
                "verbose_name_plural": "cartes",
                "ordering": ["id"],
            },
        ),
    ]
