# Generated by Django 5.1.6 on 2025-03-13 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "player_limit",
                    models.IntegerField(default=8, verbose_name="limite de joueurs"),
                ),
                ("is_open", models.BooleanField(default=True, verbose_name="ouverte")),
            ],
            options={
                "verbose_name": "salle",
                "verbose_name_plural": "salles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UnoCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=100, verbose_name="couleur")),
                ("action", models.CharField(max_length=100, verbose_name="action")),
                (
                    "image",
                    models.ImageField(upload_to="base_cards", verbose_name="image"),
                ),
                (
                    "is_special",
                    models.BooleanField(default=False, verbose_name="carte spéciale"),
                ),
            ],
            options={
                "verbose_name": "carte",
                "verbose_name_plural": "cartes",
                "ordering": ["color", "action"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="contenu")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="expéditeur",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_app.room",
                        verbose_name="salle",
                    ),
                ),
            ],
            options={
                "verbose_name": "message",
                "verbose_name_plural": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnoGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direction", models.BooleanField(verbose_name="sens du jeu")),
                (
                    "current_player_number",
                    models.IntegerField(null=True, verbose_name="joueur actuel"),
                ),
                (
                    "stored_to_draw",
                    models.IntegerField(default=0, verbose_name="cartes à piocher"),
                ),
                ("game_over", models.BooleanField(verbose_name="fin de partie")),
                (
                    "current_card",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_game_current",
                        to="api_app.unocard",
                        verbose_name="carte actuelle",
                    ),
                ),
                (
                    "pile",
                    models.ManyToManyField(
                        blank=True,
                        related_name="in_game_piles",
                        to="api_app.unocard",
                        verbose_name="pioche",
                    ),
                ),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_app.room",
                        verbose_name="salle",
                    ),
                ),
            ],
            options={
                "verbose_name": "partie",
                "verbose_name_plural": "parties",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="UnoPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_number",
                    models.IntegerField(db_index=True, verbose_name="numéro de joueur"),
                ),
                (
                    "said_uno",
                    models.BooleanField(default=False, verbose_name="a dit uno"),
                ),
                (
                    "card_back",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_game_back",
                        to="api_app.unocard",
                        verbose_name="dos de carte",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="api_app.unogame",
                        verbose_name="partie",
                    ),
                ),
                (
                    "hand",
                    models.ManyToManyField(to="api_app.unocard", verbose_name="main"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="joueur",
                    ),
                ),
            ],
            options={
                "verbose_name": "joueur",
                "verbose_name_plural": "joueurs",
                "ordering": ["user"],
            },
        ),
        migrations.AddField(
            model_name="unogame",
            name="winner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="won",
                to="api_app.unoplayer",
                verbose_name="gagnant",
            ),
        ),
    ]
