# Generated by Django 5.1.6 on 2025-03-14 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0002_cardback_remove_unoplayer_card_back_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardback",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="nom"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unogame",
            name="card_back",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api_app.cardback",
                verbose_name="dos de carte",
            ),
        ),
    ]
