# Generated by Django 5.1.6 on 2025-03-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0002_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameplayed",
            name="game_state",
        ),
        migrations.RemoveField(
            model_name="gameplayed",
            name="user",
        ),
        migrations.RemoveField(
            model_name="gamestatecard",
            name="game_state",
        ),
        migrations.RemoveField(
            model_name="room",
            name="users",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="GamePlayed",
        ),
        migrations.DeleteModel(
            name="GameState",
        ),
        migrations.DeleteModel(
            name="GameStateCard",
        ),
    ]
