# Generated by Django 5.1.6 on 2025-03-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_app",
            "0003_remove_gameplayed_game_state_remove_gameplayed_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_open",
            field=models.BooleanField(default=True, verbose_name="ouverte"),
        ),
        migrations.AddField(
            model_name="room",
            name="player_limit",
            field=models.IntegerField(default=8, verbose_name="limite de joueurs"),
        ),
    ]
