# Generated by Django 5.1.6 on 2025-03-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0003_cardback_name_unogame_card_back"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardback",
            name="image",
            field=models.ImageField(upload_to="card_back", verbose_name="image"),
        ),
        migrations.AlterField(
            model_name="cardback",
            name="price",
            field=models.IntegerField(default=0, verbose_name="prix"),
        ),
    ]
