# Generated by Django 5.1.6 on 2025-03-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0005_gameenvironment_profileeffect_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameenvironment",
            name="image",
            field=models.ImageField(
                default=1, upload_to="game_environments", verbose_name="image"
            ),
            preserve_default=False,
        ),
    ]
