# Generated by Django 5.1.6 on 2025-03-08 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0006_unocard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnoGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direction", models.BooleanField(verbose_name="sens du jeu")),
                ("game_over", models.BooleanField(verbose_name="fin de partie")),
                (
                    "current_player_number",
                    models.IntegerField(verbose_name="joueur actuel"),
                ),
                (
                    "current_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_game_current",
                        to="api_app.unocard",
                        verbose_name="carte actuelle",
                    ),
                ),
                (
                    "pile",
                    models.ManyToManyField(
                        related_name="in_game_piles",
                        to="api_app.unocard",
                        verbose_name="pioche",
                    ),
                ),
            ],
            options={
                "verbose_name": "partie",
                "verbose_name_plural": "parties",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="UnoPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_number",
                    models.IntegerField(db_index=True, verbose_name="numéro de joueur"),
                ),
                (
                    "said_uno",
                    models.BooleanField(default=False, verbose_name="a dit uno"),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="api_app.unogame",
                        verbose_name="partie",
                    ),
                ),
                (
                    "hand",
                    models.ManyToManyField(to="api_app.unocard", verbose_name="main"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="joueur",
                    ),
                ),
            ],
            options={
                "verbose_name": "joueur",
                "verbose_name_plural": "joueurs",
                "ordering": ["user"],
            },
        ),
    ]
