# Generated by Django 5.1.6 on 2025-03-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0006_gameenvironment_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="invitation_code",
            field=models.CharField(
                default=123456789,
                max_length=10,
                unique=True,
                verbose_name="code d'invitation",
            ),
            preserve_default=False,
        ),
    ]
