# Generated by Django 5.1.6 on 2025-03-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0007_room_invitation_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unogame",
            name="card_back",
        ),
    ]
