# Generated by Django 5.1.6 on 2025-03-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0011_alter_unogame_current_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unogame",
            name="stored_to_draw",
            field=models.IntegerField(default=0, verbose_name="cartes à piocher"),
        ),
    ]
