# Generated by Django 5.1.6 on 2025-03-10 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0013_unogame_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="unoplayer",
            name="card_back",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_game_back",
                to="api_app.unocard",
                verbose_name="dos de carte",
            ),
        ),
    ]
