# Generated by Django 5.1.6 on 2025-03-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0014_unoplayer_card_back"),
    ]

    operations = [
        migrations.AddField(
            model_name="unocard",
            name="is_special",
            field=models.BooleanField(default=False, verbose_name="carte spéciale"),
        ),
    ]
