# Generated by Django 5.1.6 on 2025-03-13 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0001_squashed_0015_unocard_is_special"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unogame",
            name="room",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="api_app.room",
                verbose_name="salle",
            ),
        ),
    ]
