# Generated by Django 5.1.6 on 2025-03-13 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0016_alter_unogame_room"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="joueurs",
            ),
        ),
    ]
