# Generated by Django 5.1.6 on 2025-03-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0003_customuser_cardscurrency_customuser_games_played_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
